# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:/usr/sbin:/sbin:$HOME/bin
PATH=/usr/java/jdk1.7.0_51/bin:$PATH
JAVA_HOME=/usr/java/jdk1.7.0_51/
export JAVA_HOME
export PATH
