#!/bin/bash
dialog --infobox "Entering Parameter Changing wizard" 10 30 
sleep 1
dialog --inputbox "enter the block size in MBs (Default:67108864)" 50 40 2>bf
b=`cat bf`
rm bf
dialog --inputbox "enter the replication value (Default:3)" 10 40 2>rf
r=`cat rf`
rm rf
dialog --inputbox "enter the heartbeat value (Default:10sec)" 10 40 2>hf
h=`cat hf`
rm hf
cd /root/Desktop/my_project/config/
echo '<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
	
<!-- Put site-specific property overrides in this file. -->

<configuration>
<property>
<name>dfs.name.dir</name>
<value>/tmp/node</value>
</property>
<property>
<name>dfs.block.size</name>
<value>'"$b"'</value>
</property>
<property>
<name>dfs.replication</name>
<value>'"$r"'</value>
</property>
<property>
<name>dfs.http.address</name>
<value>0.0.0.0:50070</value>
</property>
<property>
<name>dfs.heartbeat_interval</name>
<value>'"$h"'</value>
</property>
<property>
<name>dfs.hosts.exclude</name>
<value>/etc/hadoop/denyfile</value>
</property>
</configuration>' &> newhdfs-site.xml
nameip=`cat /root/Desktop/my_project/files/nn`
ssh $nameip hadoop-daemon.sh stop namenode
scp /root/Desktop/my_project/config/newhdfs-site.xml $nameip:/etc/hadoop/hdfs-site.xml
dialog --msgbox "Name node has been newly configured and stooped .. Restart name node to resume services" 10 40
bash /root/Desktop/my_project/start/hdfs1conf
