#!/bin/bash
rm /root/Desktop/my_project/files/dn
my_name=`ifconfig eth0 |grep 192|awk '{print $2}'| cut -f2 -d ":"`
dialog --msgbox "welcome to data node creation wizard " 10 40
x=`cat avai_nodes | wc -l` 
dialog --msgbox "Define policy for datanode" 7 40
dialog --inputbox "enter storage in MegaBytess" 20 40 2>str.txt
dialog --inputbox "enter RAM in MegaBytess" 20 40 2>fr.txt
str=`cat str.txt`
rm str.txt
fr=`cat fr.txt`
rm fr.txt
max=` echo "$x-1" | bc `
dialog --inputbox "how many data nodes do you want to create (maximum $max)" 50 50 2>num
y=`cat num`
rm num
dialog --menu "choose setup option" 40 50 5 "1.Auto" "" "2.Manual" "" 2>c.txt
c1=`cat c.txt`
rm c.txt
if [ $c1 == "1.Auto" ]
then
if [ $y -le $x ]
then
ax=`cat /root/Desktop/my_project/files/nn`
for i in `cat /root/Desktop/my_project/start/avai_nodes | head -$y`
do
if [ $ax == $i ]
then
echo "choose different ip as this ip belongs to namenode "
bash createdata
else 
ssh-copy-id $i
scp /root/Desktop/my_project/start/policycheck   $i:/root/Desktop/
ssh $i bash /root/Desktop/policycheck
scp $i:/root/Desktop/poli.txt  $my_name:/root/Desktop/my_project/start/
s=`cat poli.txt |grep st| cut -d: -f2`
r=`cat poli.txt |grep mem| cut -d: -f2`
echo $s
echo $r
rm poli.txt
if [ $s -gt $str -a $r -gt $fr ]
then
echo "policy satisfied"
ssh $i -t yum remove hadoop -y
ssh $i -t yum install hadoop -y
ssh $i -t yum install jdk -y
scp /root/Desktop/my_project/config/core-site.xml  $i:/etc/hadoop/core-site.xml
scp /root/Desktop/my_project/config/data-hdfs-site.xml  $i:/etc/hadoop/hdfs-site.xml
scp /root/Desktop/my_project/config/hadoop-env.sh  $i:/etc/hadoop/hadoop-env.sh.xml
scp /root/Desktop/my_project/config/bash_profile  $i:/root/.bash_profile
scp /root/Desktop/my_project/config/bashrc  $i:/root/.bashrc
ssh $i -t setenforce 0
ssh $i -t iptables -F
echo $i>>/root/Desktop/my_project/files/dn
echo $i >>/root/Desktop/my_project/files/ipused
else
echo"trying another ip"
fi
fi
done
dialog --msgbox "data nodes created " 30 30
echo "yes" > /root/Desktop/my_project/files/hdfspresent
bash hdfs1conf
else
dialog --infobox "wrong choice " 30 30
sleep 2
bash createdata
fi 
elif [ $c1 == "2.Manual" ]
then
cho=0
cp /root/Desktop/my_project/start/avai_nodes  /root/Desktop/my_project/files/ca
while [ $cho -lt $max ]
do
dialog --infobox "The available ips are " 15 30
dialog --textbox /root/Desktop/my_project/files/ca 50 50
echo enter the ip of datanode
read i
ssh-copy-id $i
scp /root/Desktop/my_project/start/policycheck   $i:/root/Desktop/
ssh $i bash /root/Desktop/policycheck
scp $i:/root/Desktop/poli.txt  $my_name:/root/Desktop/my_project/start/
s=`cat poli.txt |grep st| cut -d: -f2`
r=`cat poli.txt |grep mem| cut -d: -f2`
echo $s
echo $r
rm poli.txt
if [ $s -gt $str -a $r -gt $fr ]
then
echo "policy satisfied"
ssh $i -t yum remove hadoop -y
ssh $i -t yum install hadoop -y
ssh $i -t yum install jdk -y
scp /root/Desktop/my_project/config/core-site.xml  $i:/etc/hadoop/core-site.xml
scp /root/Desktop/my_project/config/data-hdfs-site.xml  $i:/etc/hadoop/hdfs-site.xml
scp /root/Desktop/my_project/config/hadoop-env.sh  $i:/etc/hadoop/hadoop-env.sh.xml
scp /root/Desktop/my_project/config/bash_profile  $i:/root/.bash_profile
scp /root/Desktop/my_project/config/bashrc  $i:/root/.bashrc
ssh $i -t setenforce 0
ssh $i -t iptables -F
echo $i>>/root/Desktop/my_project/files/dn
echo $i >>/root/Desktop/my_project/files/ipused
sed -i 's/$i//' /root/Desktop/my_project/files/ca 
cho=` echo "$cho +1" | bc`
fi
done
rm /root/Desktop/my_project/files/ca
bash hdfs1conf
fi
bash hdfs1conf
