#!/bin/bash
dialog --menu "Are you sure you want to continue " 30 30 5 "1.continue" "" "2.back" "" 2> yn
a=`cat yn`
rm yn
if [ $a == "1.continue" ] 
then
i=`cat /root/Desktop/my_project/files/jt`
ssh $i yum remove hadoop -y
ssh $i rmdir /tmp/node
sed -i 's/$i//' /root/Desktop/my_project/files/ipused
echo ""  >/root/Desktop/my_project/files/jt
echo "no" >/root/Desktop/my_project/files/mapreducepresent
else
bash mapreduce1conf
fi
bash mapreduce1conf
