#!/bin/bash
dialog --menu "********HADOOPV1 SETUP MENU***********" 15 40 10 "1.HDFS" ""  "2.MAPREDUCE" "" "3.HIVE" "" "4.PIG" "" "5.DATASETS" "" "6.SUMMARY" "" "7.BACK" "" 2> chv1
ch=`cat chv1`
rm chv1
if [ $ch == "1.HDFS" ]
then
bash hdfs1conf
elif [ $ch == "2.MAPREDUCE" ]
then
bash mapreduce1conf
elif [ $ch == "3.HIVE" ]
then
bash hiveconf
elif [ $ch == "4.PIG" ]
then
bash pigconf
elif [ $ch == "5.DATASETS" ]
then 
bash datasets
elif [ $ch == "6.SUMMARY" ]
then
bash summary1
elif [ $ch == "7.BACK" ]
then
bash versionmenu
fi
