#!/bin/bash
dialog --msgbox "press ok to start job tracker " 10 30
a=`cat /root/Desktop/my_project/files/jt`
ssh $a hadoop-daemon.sh start jobtracker
ssh $a jps
dialog --msgbox "task tracker started " 30 30
bash hdfs1conf
