#!/bin/bash
dialog --msg "press ok to stop Job tracker " 10 30
a=`cat /root/Desktop/my_project/files/jt`
ssh $a hadoop-daemon.sh stop jobtracker
ssh $a jps
dialog --msgbox "Job tracker service stopped" 20 30
bash hdfs1conf
