#!/bin/bash
dialog --msg "press ok to stop name node " 10 30
a=`cat /root/Desktop/my_project/files/nn`
ssh $a hadoop-daemon.sh stop namenode
ssh $a jps
dialog --msgbox "Namenode SerVice stopped" 20 30
bash hdfs1conf
